In [9]:
# han-b set kern via .ven , frmwrk
!pip install pandas numpy matplotlib mglearn seaborn scikit-learn

Requirement already satisfied: pandas in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (2.2.6)
Requirement already satisfied: matplotlib in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (3.10.8)
Requirement already satisfied: mglearn in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (0.2.0)
Requirement already satisfied: seaborn in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (1.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: imageio in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from mglearn) (2.37.2)
Requirement already satisfied: joblib in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from mglearn) (1.5.2)
Requirement already satisfied: scipy>=1.8.0 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /home/snowwy/Documents/poor_monk/poor_monk/7th_term/ai_course/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# 1. Выбор начальных условий

## a. Набор данных для задачи классификации 

Реальная практическая задача:

Выявл. тенденций в мед. страховании между сборами и мед. факторами согласн kaggle-page. 

- __Набор данных__: https://www.kaggle.com/datasets/muhammadanwaar101/healthcare-insurance-charges-dataset

## b. Набор данных для задачи регрессии 

Реальная практическая задача:

Выявл. ХБП и оценки факторов риска функции поч. согласн kaggle-page.

- __Набор данных__: https://www.kaggle.com/datasets/miadul/kidney-function-health-dataset

## c. Метрики качества и обоснование выбора

- отсылки в коммент. в коде на стр. myuller_gvido 

### Классификация:
- __Accuracy__ - процент объектов, верно классифицированных моделью. 
- __F1-score__ - среднее гармоническое между точностью (precision) и полнотой (recall).

### Регрессия:
- __MAE__ - насколько в среднем модель ошибается в прогнозах.
- __R²__ - доля дисперсии целевой переменной, которую объясняет модель. Чем ближе к 1, тем лучше.

In [10]:
# import to get framewrk's functional.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 1a. upl classif datst
# real task - factors influencing insurance charges
clf_csv_pth = "dat_reg.csv"
df_clf = pd.read_csv(clf_csv_pth)

In [ ]:
# 1b. upl regr dat
# real task - records w biomarkers 
reg_csv_pth = "dat_cl.csv"
df_reg = pd.read_csv(reg_csv_pth)

In [13]:
# observ datafrs

df_clf.head()
# вывод кортеж размерн datafr
df_clf_pd = pd.DataFrame(df_clf)
display(df_clf_pd)

# # первые строк. datafr.
df_reg.head()
df_clf.shape
# вывод обобщ. данн.
df_reg.info()

# IPython.display позволяет "красиво напечатать" датафр
df_reg_pd = pd.DataFrame(df_reg)
display(df_reg_pd) 

## Выбрать все строки, в которых значение столбца age больше 30 
display(df_reg_pd[df_reg_pd.AGE > 20])

,Creatinine,BUN,GFR,Urine_Output,Diabetes,Hypertension,Age,Protein_in_Urine,Water_Intake,Medication,CKD_Status
1501,1.157595,12.883540,93.101817,1923.517271,0,0,44.099733,107.345866,2.690923,NaN,0
2586,4.795674,63.939097,32.567352,1073.853112,0,0,46.364368,476.652101,1.778194,ARB,1
2653,0.793552,18.547813,94.980260,1611.044371,0,1,28.068343,106.368383,2.620210,NaN,0
1055,0.916492,17.488186,90.292647,2146.873184,0,0,65.761614,103.557447,3.894924,Diuretic,0
705,1.001983,16.852746,84.319003,1757.950427,1,0,67.066652,62.683154,1.732850,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...
1987,0.722519,7.944787,99.655555,2412.441089,0,0,44.967263,99.107535,3.546059,NaN,0
3648,0.615520,12.631735,90.221509,2218.831898,0,1,71.778899,82.315920,2.885668,NaN,0
344,0.910630,12.394649,93.024506,1526.252149,0,1,39.423342,148.290208,3.764337,NaN,0
4482,3.120306,60.703081,45.303095,1171.342076,0,1,39.755973,2363.703995,3.400319,NaN,1
986,6.307465,38.855448,18.040520,971.759106,0,0,55.081372,1198.997063,1.614264,ARB,1

<class 'pandas.core.frame.DataFrame'>
Index: 844 entries, 353 to 193
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   AGE                   844 non-null    int64
 1   Gender                844 non-null    object
 2   Body_Mass_Index(BMI)  844 non-null    float64
 3   Number_of_Children    844 non-null    int64
 4   Smoking_Status        844 non-null    object
 5   Region                844 non-null    object
 6   Insurance_Charges     844 non-null    float64
dtypes: float64(2), int64(2), object(3)
memory usage: 52.8+ KB

,AGE,Gender,Body_Mass_Index(BMI),Number_of_Children,Smoking_Status,Region,Insurance_Charges
353,33,male,35.245,0,no,northeast,12404.87910
864,51,male,25.400,0,no,southwest,8782.46900
1161,34,male,42.130,2,no,southeast,5124.18870
192,25,male,25.740,0,no,southeast,2137.65360
782,51,male,35.970,1,no,southeast,9386.16130
...,...,...,...,...,...,...,...
421,61,male,35.860,0,yes,southeast,46599.10840
164,37,male,29.640,0,no,northwest,5028.14660
28,23,male,17.385,1,no,northwest,2775.19215
516,20,male,35.310,1,no,southeast,27724.28875
193,56,female,26.600,1,no,northwest,12044.34200

,AGE,Gender,Body_Mass_Index(BMI),Number_of_Children,Smoking_Status,Region,Insurance_Charges
353,33,male,35.245,0,no,northeast,12404.87910
864,51,male,25.400,0,no,southwest,8782.46900
1161,34,male,42.130,2,no,southeast,5124.18870
192,25,male,25.740,0,no,southeast,2137.65360
782,51,male,35.970,1,no,southeast,9386.16130
...,...,...,...,...,...,...,...
338,50,male,32.300,1,yes,northeast,41919.09700
421,61,male,35.860,0,yes,southeast,46599.10840
164,37,male,29.640,0,no,northwest,5028.14660
28,23,male,17.385,1,no,northwest,2775.19215
193,56,female,26.600,1,no,northwest,12044.34200

In [17]:
# для классиф разделение признаков на категориальные (str_cols) и числовые (num_cols).
str_cols = df_clf.select_dtypes(include=['object']).columns.tolist()

print("Categorical variables:")
print(str_cols)

str_cols_2 = df_reg.select_dtypes(include=['object']).columns.tolist()
print("Categorical variables:")
print(str_cols_2)

Categorical variables:
['Medication']
Categorical variables:
['Gender', 'Smoking_Status', 'Region']

In [15]:
# Подсчет пропущенных значений в категориальных признаках.
for i in str_cols:
    print(i, df_clf[i].isnull().sum())

Medication 1833

In [16]:
# Заполнение пропущенных значений в категориальных признаках модой.
for i in str_cols:
    df_clf[i].fillna(df_clf[i].mode()[0], inplace=True)

/tmp/ipykernel_13356/1507480591.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clf[i].fillna(df_clf[i].mode()[0], inplace=True)

# 2. Создание бейзлайна и оценка качества

## a. Обучить модели из sklearn (для классификации и регрессии) для выбранных наборов данных

In [ ]:
## 2a.1 Подгот наб данн
### 2a.1.1 раздел датафреймовы фич на числ и катег

from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# ЗАДАЧА КЛАССИФИКАЦИИ

# Отделяем признаки (X) от целевой переменной (y)


num_cols_clf = df_clf.drop(columns=["Medication"]).select_dtypes(include=["number"]).columns.tolist()
cat_cols_clf = df_clf.drop(columns=["Medication"]).select_dtypes(include=["object"]).columns.tolist()

# В данных регрессии есть категориальные признаки (sex, smoker, region).
# Простые модели не умеют с ними работать. Для бейзлайна мы их удалим.
# df_reg_baseline = df_reg.drop(['Gender', 'Smoking_Status', 'Region'], axis=1)

# # Отделяем признаки (X) от целевой переменной (y)
# X_reg = df_reg_baseline.drop('charges', axis=1)
# y_reg = df_reg_baseline['charges']


num_cols_reg = df_reg.drop(columns=["Medication"]).select_dtypes(include=["number"]).columns.tolist()
cat_cols_reg = df_reg.drop(columns=["Medication"]).select_dtypes(include=["object"]).columns.tolist()

In [ ]:
### 2a.1.2 опред фич и тарг
X_clf = df_clf.drop(columns=["Medication"])
y_clf = df_clf["Medication"]    


X_reg = df_reg.drop(columns=["Medication"])
y_reg = df_reg["Medication"]

In [ ]:

### 2a.1.3 разб данн согл реком книг


Xclf_train, Xclf_test, yclf_train, yclf_test = train_test_split(
    X_clf, y_clf, test_size=0.25, random_state=0
)

Xreg_train, Xreg_test, yreg_train, yreg_test = train_test_split(
    X_reg, y_reg, test_size=0.25, random_state=0
)

In [ ]:

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score, f1_score
from category_encoders import TargetEncoder
from sklearn.model_selection import GridSearchCV
from collections import Counter
from sklearn.metrics import ConfusionMatrixDisplay

In [ ]:
### 2a.2 Обуч мод

# для clf масшт. числ фич by OneH
prep_clf = ColumnTransformer(transformers=[
        ("num", StandardScaler(), num_cols_clf),
        ("cat", OneHotEncoder(handle_unknown="ignore"), 
         cat_cols_clf),]
)

basel_clf = Pipeline([
    ("prep", prep_clf), ("model", KNeighborsClassifier())]
)

basel_clf.fit(Xclf_train, yclf_train)
# чтоб сдел. прогн., выз. predict объекта
yclf_pred = basel_clf.predict(Xclf_test)

# обосн выбор метр
acur = accuracy_score(yclf_test, yclf_pred)
f_1 = f1_score(yclf_test, yclf_pred)

In [ ]:
# обычная регрессия

# масшт. числ. featu. via OneH
preprocessor_reg = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols_reg),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols_reg),
    ]
)


reg_baseline = Pipeline([
    ("prep", preprocessor_reg),
    ("model", KNeighborsRegressor())
])

reg_baseline.fit(Xreg_train, yreg_train)
# чтоб сдел. прогн., выз. predict объекта
yreg_pred = reg_baseline.predict(Xreg_test)


mae = mean_absolute_error(yreg_test, yreg_pred)
rmse = np.sqrt(mean_squared_error(yreg_test, yreg_pred))
r2 = r2_score(yreg_test, yreg_pred)

## b. Оценить качество моделей (для классификации и регрессии) по выбранным метрикам на выбранных наборах данных

In [ ]:
# 2.b. Оценить качество моделей (для классификации и регрессии) по выбранным метрикам на выбранных наборах данных
print("Classif metr: ", acur, f_1)
print("Regr metr: ", mae, rmse, r2)


y_pred = knn.predict(X_test) 
print("Прогнозы для тестового набора:\n {}".format(y_pred))


# - обосн: с 38 myulr_gvid
print("Правильность на тестовом наборе: {:.2f}".format(np.mean(y_pred == y_test))) 
print("Правильность на тестовом наборе: {:.2f}".format(knn.score(X_test, y_test)))

In [ ]:
# upl class datst
clas_dat = pd.read_csv(".csv", sep='\t')
print(clas_dat.shape)

# 3. Улучшение бейзлайна

## a. Сформулировать гипотезы (препроцессинг данных, визуализация данных, формирование новых признаков, подбор гиперпараметров на кросс-валидации и т.д.)

## b. Проверить гипотезы

## c. Сформировать улучшенный бейзлайн по результатам проверки гипотез

## d. Обучить модели с улучшенным бейзлайном (для классификации и регрессии) для выбранных наборов данных

## d. Обучить модели с улучшенным бейзлайном (для классификации и регрессии) для выбранных наборов данных

## e. Оценить качество моделей с улучшенным бейзлайном (для классификации и регрессии) по выбранным метрикам на выбранных наборах данных

## f. Сравнить результаты моделей с улучшенным бейзлайном в сравнении с результатами из пункта 2 

## g. Сделать выводы

In [ ]:
# улучшенная классификация

# используем TargetEncoder вместо OneHot
prep_clf_imp = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols_clf),
        ("cat", TargetEncoder(), cat_cols_clf),
    ]
)

clf_pipe = Pipeline([
    ("prep", prep_clf_imp),
    ("model", KNeighborsClassifier())
])

# подбираем гиперпараметры через GridSearchCV
params = {
    "model__n_neighbors": [3, 5, 7],
    "model__weights": ["uniform", "distance"],
    "model__metric": ["euclidean", "manhattan"]
}

clf_grid = GridSearchCV(
    clf_pipe,
    params,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

clf_grid.fit(Xclf_train, yclf_train)

print("лучшие параметры:", clf_grid.best_params_)
best_clf = clf_grid.best_estimator_
yclf_pred_imp = best_clf.predict(Xclf_test)

acc_imp = accuracy_score(yclf_test, yclf_pred_imp)
f1_imp = f1_score(yclf_test, yclf_pred_imp)

print(acc_imp, f1_imp)

ConfusionMatrixDisplay.from_predictions(
    yclf_test,
    yclf_pred_imp,
    cmap="Blues"
)

In [ ]:
# улучшенная регрессия

# используем TargetEncoder вместо OneHot
preprocessor_reg_imp = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols_reg),
        ("cat", TargetEncoder(), cat_cols_reg),
    ]
)

reg_pipe = Pipeline([
    ("prep", preprocessor_reg_imp),
    ("model", KNeighborsRegressor())
])

# подбираем гиперпараметры через GridSearchCV
reg_grid = GridSearchCV(
    reg_pipe,
    params,
    cv=5,
    scoring="neg_mean_absolute_error",
    n_jobs=-1
)

reg_grid.fit(Xreg_train, yreg_train)

print("лучшие параметры:", reg_grid.best_params_)
best_reg = reg_grid.best_estimator_
yreg_pred_imp = best_reg.predict(Xreg_test)

mae_imp = mean_absolute_error(yreg_test, yreg_pred_imp)
rmse_imp = np.sqrt(mean_squared_error(yreg_test, yreg_pred_imp))
r2_imp = r2_score(yreg_test, yreg_pred_imp)

print(mae_imp, rmse_imp, r2_imp)

plt.scatter(yreg_train, yreg_pred_imp, alpha=0.5)
plt.plot([yreg_train.min(), yreg_train.max()],
         [yreg_train.min(), yreg_train.max()],
         linestyle="--")
plt.xlabel("факт")
plt.ylabel("предсказание")
plt.title("факт vs предсказание")
plt.show()

In [ ]:
# upl regr datst
regr_dat = pd.read_csv(".csv")
print(regr_dat.shape)

In [ ]:
# clasif clas distr: 1) value_counts, 2)describe

# 4. Имплементация алгоритма машинного обучения 

## a. Самостоятельно имплементировать алгоритмы машинного обучения (для классификации и регрессии)

## b. Обучить имплементированные модели (для классификации и регрессии) для выбранных наборов данных

## c. Оценить качество имплементированных моделей (для классификации и регрессии) по выбранным метрикам на выбранных наборах данных

## d. Сравнить результаты имплементированных моделей в сравнении с результатами из пункта 2

## e. Сделать выводы

In [ ]:
# по книг, n_neighb = 1

class MyKNNСlf:
    
    def __init__(self, n_neighbors=1, metric="euclidean"):
        self.k = n_neighbors
        self.metric = metric

    def fit(self, X, y):
        # Просто запоминает данные
        self.X_train = np.array(X)
        self.y_train = np.array(y)
        return self

    def distance(self, a, b):
        if self.metric == "euclidean":
            return np.sqrt(np.sum((a - b) ** 2))
        elif self.metric == "manhattan":
            return np.sum(np.abs(a - b))

    def predict(self, X):
        X = np.array(X)
        predictions = []

        for x in X:
            distances = np.array([self.distance(x, train_x) for train_x in self.X_train])
            k_idx = distances.argsort()[:self.k]
            k_labels = self.y_train[k_idx]
            most_common = Counter(k_labels).most_common(1)[0][0]
            predictions.append(most_common)

        return np.array(predictions)

# используем улучшенный препроцессор
my_clf_pipe = Pipeline([
    ("prep", prep_clf_imp),
    ("model", MyKNNСlf(n_neighbors=3, metric="euclidean"))
])

my_clf_pipe.fit(Xclf_train, yclf_train)
yclf_pred_my = my_clf_pipe.predict(Xclf_test)

acc_my = accuracy_score(yclf_test, yclf_pred_my)
f1_my = f1_score(yclf_test, yclf_pred_my)

print(acc_my, f1_my)

In [ ]:
# своя регрессия

class MyKNNReg:
    def __init__(self, n_neighbors=3, metric="manhattan"):
        self.k = n_neighbors
        self.metric = metric

    def fit(self, X, y):
        self.X_train = np.array(X)
        self.y_train = np.array(y)
        return self

    def distance(self, a, b):
        if self.metric == "euclidean":
            return np.sqrt(np.sum((a - b) ** 2))
        elif self.metric == "manhattan":
            return np.sum(np.abs(a - b))

    def predict(self, X):
        X = np.array(X)
        preds = []

        for x in X:
            distances = np.array([self.distance(x, train_x) for train_x in self.X_train])
            k_idx = distances.argsort()[:self.k]
            preds.append(np.mean(self.y_train[k_idx]))

        return np.array(preds)

# используем улучшенный препроцессор
my_reg_pipe = Pipeline([
    ("prep", preprocessor_reg_imp),
    ("model", MyKNNReg(n_neighbors=3, metric="manhattan"))
])

my_reg_pipe.fit(Xreg_train, yreg_train)
yreg_pred_my = my_reg_pipe.predict(Xreg_test)

mae_my = mean_absolute_error(yreg_train, yreg_pred_my)
rmse_my = np.sqrt(mean_squared_error(yreg_train, yreg_pred_my))
r2_my = r2_score(yreg_train, yreg_pred_my)

print(mae_my, rmse_my, r2_my)


## f. Добавить техники из улучшенного бейзлайна (пункт 3с)

## g. Обучить модели (для классификации и регрессии) для выбранных наборов данных

## h. Оценить качество моделей (для классификации и регрессии) по выбранным метрикам на выбранных наборах данных

## i. Сравнить результаты моделей в сравнении с результатами из пункта 3

## j. Сделать выводы

In [ ]:
# сравнение всех реализаций между собой
# по итогам замеров - лучше всего себя показывает улучшенный бейзлайн

print("\nклассификация\n")
print("модель\t\t\tAccuracy\tF1-score")
print(f"SKL бейзлайн\t\t{acc:.4f}\t\t{f1:.4f}")
print(f"SKL улучшенная\t\t{acc_imp:.4f}\t\t{f1_imp:.4f}")
print(f"MyKNN\t\t\t{acc_my:.4f}\t\t{f1_my:.4f}")

print("\nрегрессия\n")
print("модель\t\t\tMAE\t\tRMSE\t\tR²")
print(f"SKL бейзлайн\t\t{mae:.2f}\t\t{rmse:.2f}\t\t{r2:.4f}")
print(f"SKL улучшенная\t\t{mae_imp:.2f}\t\t{rmse_imp:.2f}\t\t{r2_imp:.4f}")
print(f"MyKNN\t\t\t{mae_my:.2f}\t\t{rmse_my:.2f}\t\t{r2_my:.4f}")